#Essential Library

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

#Supervised Technique for word embedding 

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
print(one_hot('amazing restaurant', 500)) # review , vocab size
print(one_hot('amazing restaurant', 30))  # review , vocab size

[19, 451]
[11, 17]


In [6]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[17, 10], [11, 17], [8, 14], [10, 25, 10], [21, 25, 25], [4, 10], [26, 25, 14], [17, 26], [17, 9], [13, 13]]


In [8]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
print(padded_reviews)

[[17 10  0]
 [11 17  0]
 [ 8 14  0]
 [10 25 10]
 [21 25 25]
 [ 4 10  0]
 [26 25 14]
 [17 26  0]
 [17  9  0]
 [13 13  0]]


In [12]:
embedded_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length = max_length, name = 'embedding'))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [13]:
X = padded_reviews
y = sentiment

In [14]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X, y, epochs = 50, verbose = 0)

In [16]:
loss, accuracy = model.evaluate(X, y)

1/1 [==============================] - 0s 286ms/step - loss: 0.6355 - accuracy: 0.9000


In [19]:
weights = model.get_layer('embedding').get_weights()[0]

In [18]:
len(model.get_layer('embedding').get_weights()[0])

30

In [20]:
weights[17]

array([ 0.05248594,  0.09482823, -0.00451619, -0.10544565], dtype=float32)

In [21]:
weights[11]

array([-0.0597672 , -0.09339109, -0.0893216 ,  0.05606331], dtype=float32)